const displayText = {
    pl: {
        start: `Start`,
        settings: `Ustawienia`,
        restoreSettings: `Domyślne`,
        animationGroup: `Animacja`,
        zoomGroup: `Zoom`,
        newGroup:'New',
        stickyCell:'Sticky cell (RMB & LMB)',
        'macroFeeding': 'Macro feed (80ms)',
        'renderQuality':'Rendering quality (1)',
        'debug':'Debug',
        'mapLocalFix3':'Map Fix on re-join',
        'mapGlobalFix4':'Map Global Fix (from LM)',
        'experimental1':'Experimental improvement №1',
        'cameraDelay':'Camera delay (0)',
        zoomSmoothness:'Zoom Smoothness (10)',
        'showExtraMiniMapGuides':'Show extra minimap guides',
        respGroup: `Odrodzenie`,
        namesGroup: 'Nazwy',
        massGroup: 'Masa',
        skinsGroup: `Skiny`,
        foodGroup: `Pokarm`,
        transparencyGroup: `Przezroczystość / kolory`,
        gridGroup: `Siatka / sektory`,
        miniMapGroup: `Minimapa`,
        helpersGroup: `Wspomagacze`,
        mouseGroup: `Sterowanie myszką`,
        hudGroup: `HUD`,
        chatGroup: `Czat`,
        statsGroup: 'Statystyki',
        extrasGroup: `Dodatkowe`,
        noSkins: `Wyłącz skiny`,
        noNames: 'Wyłącz nazwy',
        noColors: `Wyłącz kolory`,
        showMass: 'Pokaż masę',
        skipStats: `Pomiń statystyki po śmierci`,
        showQuest: `Pokaż zadanie (quest)`,
        autoZoom: `Auto zoom`,
        animation: `Opóźnienie animacji`,
        zoomSpeedValue: `Szybkość zoomu`,
        quickResp: `Szybkie odrodzenie (klawisz)`,
        autoResp: 'Auto odrodzenie',
        autoHideCellsInfo: `Autoukrywanie nazw i masy`,
        autoHideNames: `Autoukrywanie nazw`,
        autoHideMass: `Autoukrywanie masy`,
        autoHideFood: `Autoukrywanie pokarmu (masa)`,
        autoHideFoodOnZoom: `Autoukrywanie pokarmu (zoom)`,
        optimizedNames: `Zoptymalizowane nazwy`,
        hideMyName: `Ukryj własną nazwę`,
        hideTeammatesNames: `Ukryj nazwy graczy teamu`,
        optimizedMass: `Zoptymalizowana masa (+/-2%)`,
        shortMass: `Skrócona masa (k)`,
        virMassShots: `Licznik strzałów (wirusy)`,
        hideMyMass: `Ukryj własną masę`,
        hideEnemiesMass: 'Ukryj masę przeciwników',
        vanillaSkins: `Podstawowe skiny`,
        customSkins: 'Własne skiny',
        myTransparentSkin: `Mój przezroczysty skin`,
        myCustomColor: `Mój własny kolor`,
        transparentCells: `Przezroczyste kulki`,
        transparentViruses: `Przezroczyste wirusy`,
        transparentSkins: 'Przezroczyste skiny',
        showGrid: `Siatka`,
        showBgSectors: 'Sektory w tle',
        showMapBorders: `Granice mapy`,
        showGhostCells: `Duchy kulek`,
        showMiniMap: `Pokaż minimapę`,
        showMiniMapGrid: `Pokaż siatkę minimapy`,
        showMiniMapGuides: 'Pokaż prowadnice na minimapie',
        showMiniMapGhostCells: `Pokaż duchy kulek na minimapie`,
        oneColoredTeammates: `Jednokolorowi gracze`,
        optimizedFood: 'Zoptymalizowany pokarm',
        rainbowFood: `Kolorowy pokarm`,
        oppColors: 'Kolory przeciwników',
        oppRings: `Ringi przeciwników`,
        virColors: `Kolory wirusów`,
        splitRange: `Zasięg podziału`,
        virusesRange: `Zasięg wirusów`,
        textStroke: `Obwódki nazw i masy`,
        namesStroke: `Obwódki nazw`,
        massStroke: `Obwódki masy`,
        cursorTracking: 'Śledzenie kursora',
        teammatesInd: `Wskaźniki graczy teamu`,
        mouseSplit: `LPM - Split myszką`,
        mouseFeed: `PPM - Feed myszką`,
        mouseInvert: `Odwróć klawisze myszki`,
        disableChat: `Wyłącz czat`,
        hideChat: `Ukryj czat`,
        chatSounds: 'Powiadomienia dźwiękowe',
        chatEmoticons: `Emotikony`,
        showChatImages: 'Pokaż obrazki na czacie',
        showChatVideos: 'Pokaż filmiki na czacie',
        showChatBox: `Czatbox zamiast wyskakujących wiadomości`,
        messageSound: `Dźwięk powiadomienia o wiadomości`,
        commandSound: `Dźwięk powiadomienia o komendzie`,
        virusSounds:'Virus eject sound',
        virusSoundURL:'Virus eject sound URL',
        showTop5: `Pokaż top 5 teamu`,
        showTop5Sectors:'Show top 5 sectors',
        showTargeting: 'Pokaż namierzanie',
        showTime: `Pokaż aktualny czas`,
        showLbData: 'Pokaż masę w topce',
        normalLb: `Nagłówek "Topka"`,
        centeredLb: `Wyśrodkowana topka`,
        fpsAtTop: `Statystyki na górze`,
        showStats: `Pokaż statystyki`,
        showStatsMass: `Statystyki: Masa`,
        showStatsSTE: `Statystyki: STE`,
        showStatsN16: `Statystyki: n/16`,
        showStatsFPS: `Statystyki: FPS`,
        'showStatsPPS': 'Statystyki: PPS',
        blockPopups: `Blokuj popupy (reklamy/sklep/zadanie)`,
        hotkeys: 'Skróty klawiszowe',
        'hk-switchPlayer':'Switch player',
        'hk-inst-assign': `Aby ustawić skrót klawiszowy kliknij na polu skrótu i naciśnij wybrany klawisz.`,
        'hk-inst-delete': `Aby usunąć skrót klawiszowy kliknij na polu skrótu i naciśnij klawisz DELETE.`,
        'hk-inst-keys': `Możliwe kombinacje skrótów klawiszowych z użyciem klawiszy CTRL oraz ALT.`,
        'hk-bots-split': 'Bots split',
        'hk-bots-feed': 'Bots feed',
        'hk-bots-ai': 'Bots AI toggle',
        'hk-feed': `Feed`,
        'hk-macroFeed': 'Szybki feed',
        'hk-split': `Podział`,
        'hk-doubleSplit': `Podwójny podział`,
        'hk-tripleSplit': `Triple split`,
        'hk-split16': `Podział na 16`,
        'hk-pause': `Pauza kulki`,
        'hk-showTop5': `Pokaż/ukryj top 5 teamu`,
        'hk-showTime': `Pokaż/ukryj aktualny czas`,
        'hk-showSplitRange': `Pokaż/ukryj zasięg podziału`,
        'hk-showSplitInd': `Pokaż/ukryj zasięg podziału z ringami`,
        'hk-showTeammatesInd': `Pokaż/ukryj wskaźniki graczy teamu`,
        'hk-showOppColors': `Pokaż/ukryj kolory przeciwników`,
        'hk-toggleSkins': `Przełącz skiny (własne/standardowe)`,
        'hk-showSkins': `Pokaż/ukryj skiny`,
        'hk-transparentSkins': `Włącz/wyłącz przezroczyste skiny`,
        'hk-showStats': `Pokaż/ukryj statystyki gry`,
        'hk-toggleCells': `Przełącz kulkę (najmniejsza/największa)`,
        'hk-showFood': 'Pokaż/ukryj pokarm',
        'hk-showGrid': 'Pokaż/ukryj siatkę',
        'hk-showMiniMapGuides': `Pokaż/ukryj prowadnice na minimapie`,
        'hk-hideChat': `Pokaż/ukryj czat`,
        'hk-showHUD': `Pokaż/ukryj HUD`,
        'hk-copyLb': `Kopiuj topkę`,
        'hk-showLb': `Pokaż/ukryj topkę`,
        'hk-toggleAutoZoom': 'Włącz/wyłącz auto zoom',
        'hk-resetZoom': `Reset zoomu`,
        'hk-zoomLevel': `Zoom - poziom`,
        'hk-toggleDeath': `Przełącz miejsce śmierci`,
        'hk-clearChat': `Pokaż historię czatu / Czyść czat`,
        'hk-showBgSectors': 'Pokaż/ukryj sektory w tle',
        'hk-hideBots': 'Pokaż/ukryj małe boty',
        'hk-showNames': `Pokaż/ukryj nazwy`,
        'hk-hideTeammatesNames': `Pokaż/ukryj nazwy graczy teamu`,
        'hk-showMass': 'Pokaż/ukryj masę',
        'hk-showMiniMap': `Pokaż/ukryj minimapę`,
        'hk-chatMessage': `Napisz wiadomość na czacie`,
        'hk-quickResp': `Szybkie odrodzenie (respawn)`,
        'hk-autoResp': `Włącz/wyłacz auto odrodzenie`,
        'hk-switchServerMode': `Przełącz serwer [publiczny/prywatny]`,
        'hk-showTargeting': `Pokaż/ukryj panel namierzania`,
        'hk-setTargeting': 'Włącz/wyłącz namierzanie (śledzenie)',
        'hk-cancelTargeting': `Zatrzymaj namierzanie`,
        'hk-changeTarget': `Zmień cel`,
        'hk-privateMiniMap': `Pokaż cel na minimapie`,
        'hk-showQuest': `Pokaż/ukryj zadanie`,
        commands: `Komendy`,
        comm1: 'Feeduj!',
        comm2: 'Dziel się!',
        comm3: `Pomocy na %currentSector%!`,
        comm4: `Wróg na %currentSector%!`,
        comm5: `Zabij pomocnika!`,
        comm6: `Strzel z wirusa!`,
        comm7: `Zjedz wirusa!`,
        comm8: `Zjebałem, wybacz.`,
        comm9: `Ja pierdolę...`,
        comm0: `Kurwa mać!`,
        comm10: 'Trick!',
        comm11: `Lewo!`,
        comm12: `Góra!`,
        comm13: `Prawo!`,
        comm14: `Dół!`,
        saveComm: `Zapisz komendy`,
        theme: 'Wygląd',
        restoreThemeSettings: `Przywróc ustawienia domyślne wyglądu`,
        basicTheming: `Podstawowy`,
        themePreset: `Motyw`,
        themeType: 'Typ motywu',
        darkTheme: `Ciemny motyw`,
        lightTheme: 'Jasny motyw',
        mainColor: `Kolor główny`,
        bgColor: 'Tło',
        bordersColor: `Granice mapy`,
        gridColor: `Siatka`,
        sectorsColor: `Czcionka sektorów`,
        namesColor: `Nazwy`,
        namesStrokeColor: `Obwódki nazw`,
        massColor: `Masa`,
        massStrokeColor: `Obwódki masy`,
        virusColor: `Wirusy`,
        virusStrokeColor: 'Obwódki wirusów',
        foodColor: `Pokarm`,
        namesFont: 'Czcionka nazw',
        massFont: `Czcionka masy`,
        sectorsFont: `Czcionka sektorów`,
        namesScale: 'Skala nazw',
        massScale: 'Skala masy',
        virMassScale: `Skala masy wirusów`,
        strokeScale: `Skala obwódek tekstu`,
        foodSize: 'Wielkość pokarmu',
        bordersWidth: 'Grubość granic mapy',
        sectorsWidth: `Grubość siatki sektorów`,
        sectorsFontSize: `Rozmiar czcionki sektorów`,
        cellsAlpha: `Przezroczystość kulek`,
        skinsAlpha: `Przezroczystość skinów`,
        virusAlpha: `Przezroczystość wirusów`,
        textAlpha: 'Przezroczystość nazw i masy',
        virusStrokeSize: `Grubość obwódki wirusów`,
        teammatesIndColor: `Wskaźnik gracza`,
        cursorTrackingColor: 'Śledzenie kursora',
        splitRangeColor: `Zasięg podziału`,
        safeAreaColor: `Bezpieczna strefa`,
        dangerAreaColor: 'Strefa zagrożenia',
        ghostCellsColor: `Duchy kulek`,
        ghostCellsAlpha: 'Przezroczystość duchów kulek',
        menuTheming: `Menu`,
        menuPreset: `Motyw menu`,
        menuMainColor: `Kolor główny`,
        menuBtnTextColor: 'Tekst przycisku',
        menuPanelColor: `Panel`,
        menuPanelColor2: `Panel (2)`,
        menuTextColor: `Tekst panelu`,
        menuTextColor2: 'Tekst panelu (2)',
        btn1Color: `Przycisk #1`,
        btn1Color2: 'Przycisk #1 (2)',
        btn2Color: `Przycisk #2`,
        btn2Color2: `Przycisk #2 (2)`,
        btn3Color: `Przycisk #3`,
        btn3Color2: 'Przycisk #3 (2)',
        btn4Color: `Przycisk #4`,
        btn4Color2: `Przycisk #4 (2)`,
        menuBg: 'Grafika tła panelu',
        menuOpacity: 'Przezroczystość',
        hudTheming: `HUD`,
        hudMainColor: `Kolor główny`,
        hudColor: `Tło`,
        hudTextColor: 'Tekst',
        statsHudColor: `Statystyki`,
        timeHudColor: 'Czas',
        top5MassColor: `Masa`,
        lbMeColor: `Topka - ja`,
        lbTeammateColor: `Topka - team`,
        hudFont: `Czcionka HUD`,
        hudScale: `Skala HUD`,
        chatTheming: 'Czat',
        messageColor: 'Tło wiadomości',
        messageTextColor: 'Tekst wiadomości',
        messageTimeColor: `Czas wiadomości`,
        messageNickColor: `Nick wiadomości`,
        commandsColor: `Tło komendy`,
        commandsTextColor: `Tekst komendy`,
        commandsTimeColor: 'Czas komendy',
        commandsNickColor: `Nick komendy`,
        chatBoxColor: `Tło czatboxu`,
        chatScale: `Skala czatu`,
        miniMapTheming: `Minimapa`,
        miniMapSectorsColor: `Sektory`,
        miniMapSectorColor: `Aktualny sektor`,
        miniMapGuidesColor: `Prowadnice`,
        miniMapNickColor: 'Nick',
        miniMapNickStrokeColor: `Obwódka nicku`,
        miniMapMyCellColor: 'Moja kulka',
        miniMapMyCellStrokeColor: `Obwódka mojej kulki`,
        miniMapTeammatesColor: 'Gracze',
        miniMapDeathLocationColor: `Miejsce śmierci`,
        miniMapFont: `Czcionka minimapy`,
        miniMapNickFont: `Czcionka nicku`,
        miniMapWidth: `Szerokość minimapy`,
        miniMapSectorsOpacity: 'Przezroczystość sektorów',
        miniMapNickSize: `Rozmiar nicku`,
        miniMapNickStrokeSize: `Grubość obwódki nicku`,
        miniMapMyCellSize: `Wielkość mojej kulki`,
        miniMapMyCellStrokeSize: `Grubość obwódki mojej kulki`,
        miniMapTeammatesSize: `Wielkość graczy`,
        miniMapGhostCellsColor: `Duchy kulek`,
        miniMapGhostCellsAlpha: `Przezroczystość duchów kulek`,
        imagesTheming: 'Grafika / kursory',
        customBackground: `Grafika tła`,
        'customMapTexture': 'Grafika mapy',
        'customMapLogo': 'Logo mapy',
        customCursor: `Grafika kursora`,
        hideChatMsgA: `Czat został włączony!`,
        hideChatMsgB: `Czat został ukryty!`,
        showSkinsMsgA: 'Skiny zostały włączone!',
        showSkinsMsgB: `Skiny zostały ukryte!`,
        hideSmallBotsMsgA: 'Małe boty stały się widoczne!',
        hideSmallBotsMsgB: 'Małe boty zostały ukryte!',
        autoRespMsgA: `Auto odrodzenie zostało włączone!`,
        autoRespMsgB: `Auto odrodzenie zostało wyłączone!`,
        autoZoomMsgA: `Auto zoom został włączony!`,
        autoZoomMsgB: 'Auto zoom został wyłączony!',
        targetNotSet: `Brak celu`,
        targetDead: `Nie żyje`,
        targetDistance: 'Dystans',
        targetMass: `Masa razem`,
        totalPartyPlayers: 'Aktywnych graczy',
        totalPartyMass: 'Łącznie masy',
        exportImport: `Eksport / import ustawień`,
        exportSettings: `Eksportuj ustawienia`,
        exportInfo: 'Aby wyeksportować wybrane ustawienia skopiuj poniższy kod i zapisz go w pliku tekstowym z kodowaniem Unicode.',
        importSettings: 'Importuj ustawienia',
        importInfo: `Aby zaimportować wybrane ustawienia wklej poniżej wyeksportowany wcześniej kod i naciśnij przycisk "Importuj ustawienia".`,
        profile: `Profil`,
        profiles: `Profile`,
        skins: 'Skiny',
        moreSkins: `Dodaj skiny`,
        thanks: `Dzięki Awesome!`,
        saveSett: `Zapisz ustawienia`,
        saved: 'Zapisano!',
        resetSett: `Resetuj ustawienia`,
        close: `Zamknij`,
        enterChatMsg: `Napisz wiadomość`,
        activeParties: `Aktywne party`,
        noActiveParties: `Brak aktywnych party ;(`,
        playlist: `Playlista`,
        pause: `PAUZA!`,
        visit: `Odwiedź`,
        exit: 'OGARio by szymy: Czy na pewno chcesz opuścic grę?',
        blockWarn: `UWAGA! Popupy zostały zablokowane w ustawieniach.`,
        unblockPopups: `Odblokuj tymczasowo`,
        mass: `Masa`,
        score: `Top`,
        leaderboard: `Topka`,
        leaderboardLength:'Length of Leaderboard (10)',
        user: `Użytkownik`,
        userMuted: `Użytkownik %user% został wyciszony.`,
        userUnmuted: `Wyłączono wyciszenie użytkownika %user%.`,
        mute: `Wycisz`,
        unmute: 'Wyłącz wyciszenie',
        mutedUsers: `Wyciszeni użytkownicy`,
        activeUsers: `Aktywni użytkownicy`,
        showActiveUsers: 'Pokaż aktywnych użytkowników',
        none: `Brak`,
        sounds: 'Dźwięki',
        page_back_button: `Wróć`,
        page_create_party: `Stwórz party`,
        page_join_party: `Dołącz`,
        page_login_and_play: `Zaloguj`,
        page_logout: `Wyloguj`,
        page_menu_login_facebook: `Zaloguj z Facebook`,
        page_menu_login_google: 'Zaloguj z Google',
        page_menu_main_free_coins: `Darmowe Monety`,
        page_menu_main_gifts: 'Prezenty',
        page_menu_main_dailyquests: `Zadania`,
        page_party_join_error: 'Nie można dołączyć do tego party. Upewnij się, że token jest prawidłowy lub stwórz nowy.',
        page_play: `Graj`,
        page_play_as_guest: `Graj jako gość`,
        page_shop: `Sklep`,
        page_spectate: `Obserwuj`,
        page_stats: `Statystyki`
    },
    en: {
        start: `Home`,
        settings: `Settings`,
        restoreSettings: `Restore`,
        animationGroup: `Animation`,
        zoomGroup: `Zoom`,
        newGroup:'New',
        stickyCell:'Sticky cell (RMB & LMB)',
        'macroFeeding': 'Macro feeding (80ms)',
        'renderQuality':'Rendering quality (1)',
        'debug':'Debug',
        'mapLocalFix3':'Map Fix on re-join',
        'mapGlobalFix4':'Map Global Fix (from LM)',
        'experimental1':'Experimental improvement №1',
        cameraDelay:'Camera delay (0)',
        zoomSmoothness:'Zoom Smoothness (10)',
        'showExtraMiniMapGuides':'Show extra minimap guides',
        respGroup: `Respawn`,
        namesGroup: `Names`,
        massGroup: 'Mass',
        skinsGroup: `Skins`,
        foodGroup: `Food`,
        transparencyGroup: 'Transparency / colors',
        gridGroup: 'Grid / sectors',
        miniMapGroup: `Minimap`,
        helpersGroup: `Helpers`,
        mouseGroup: `Mouse control`,
        hudGroup: `HUD`,
        chatGroup: `Chat`,
        statsGroup: `Stats`,
        extrasGroup: `Extras`,
        noSkins: `No skins`,
        noNames: 'No names',
        noColors: 'No colors',
        showMass: `Show mass`,
        skipStats: 'Skip stats after death',
        showQuest: `Show quest`,
        autoZoom: `Auto zoom`,
        animation: `Animation delay`,
        zoomSpeedValue: `Zoom speed`,
        quickResp: `Quick respawn (hotkey)`,
        autoResp: `Auto respawn`,
        autoHideCellsInfo: `Auto hide names and mass`,
        autoHideNames: `Auto hide names`,
        autoHideMass: `Auto hide mass`,
        autoHideFood: `Auto hide food (mass)`,
        autoHideFoodOnZoom: 'Auto hide food (zoom)',
        optimizedNames: `Optimized names`,
        hideMyName: `Hide my name`,
        hideTeammatesNames: `Hide teammates names`,
        optimizedMass: `Optimized mass (+/-2%)`,
        shortMass: `Short mass (k)`,
        virMassShots: `Virus shots`,
        hideMyMass: `Hide my mass`,
        hideEnemiesMass: `Hide enemies mass`,
        vanillaSkins: `Vanilla skins`,
        customSkins: `Custom skins`,
        myTransparentSkin: `My transparent skin`,
        myCustomColor: `My custom color`,
        transparentCells: `Transparent cells`,
        transparentViruses: 'Transparent viruses',
        transparentSkins: 'Transparent skins',
        showGrid: 'Show grid',
        showBgSectors: `Show background sectors`,
        showMapBorders: `Show map borders`,
        showGhostCells: `Ghost cells`,
        showMiniMap: `Show minimap`,
        showMiniMapGrid: `Show minimap grid`,
        showMiniMapGuides: `Show minimap guides`,
        showMiniMapGhostCells: `Show ghost cells`,
        oneColoredTeammates: 'One-colored teammates',
        optimizedFood: `Optimized food`,
        rainbowFood: `Rainbow food`,
        oppColors: `Opponents colors`,
        oppRings: `Opponents rings`,
        virColors: `Viruses colors`,
        splitRange: `Split range`,
        virusesRange: 'Viruses range',
        textStroke: `Names and mass stroke`,
        namesStroke: 'Names stroke',
        massStroke: `Mass stroke`,
        cursorTracking: 'Cursor tracking',
        teammatesInd: `Teammates indicators`,
        mouseSplit: `LMB - Mouse split`,
        mouseFeed: `RMB - Mouse feed`,
        mouseInvert: `Invert mouse buttons`,
        disableChat: 'Disable chat',
        hideChat: `Hide chat`,
        chatSounds: `Sound notifications`,
        chatEmoticons: `Emoticons`,
        showChatImages: 'Show images on chat',
        showChatVideos: `Show videos on chat`,
        showChatBox: `Chatbox instead of popups`,
        messageSound: `Message notification sound`,
        commandSound: `Command notification sound`,
        virusSounds: `Virus eject sound`,
        virusSoundURL:'Virus eject sound URL',
        showTop5: 'Show team top 5',
        showTop5Sectors:'Show team top 5 sectors',
        showTargeting: `Show targeting`,
        showTime: 'Show current time',
        showLbData: `Show leaderboard mass`,
        normalLb: `"Leaderboard" header`,
        centeredLb: `Centered leaderboard`,
        fpsAtTop: `Game stats at the top`,
        showStats: `Show game stats`,
        showStatsMass: `Game stats: Mass`,
        showStatsSTE: `Game stats: STE`,
        showStatsN16: `Game stats: n/16`,
        showStatsFPS: `Game stats: FPS`,
        'showStatsPPS': 'Game stats: PPS',
        blockPopups: `Block popups (ads/shop/quest)`,
        hotkeys: 'Hotkeys',
        'hk-switchPlayer':'Switch player',
        'hk-inst-assign': `To assign a hotkey click on the input field and press your chosen key.`,
        'hk-inst-delete': `To delete a hotkey click on the input field and press the DELETE key.`,
        'hk-inst-keys': `Possible key combinations with the CTRL and ALT keys.`,
        'hk-bots-split': 'Bots split',
        'hk-bots-feed': 'Bots feed',
        'hk-bots-ai': 'Bots AI toggle',
        'hk-feed': 'Feed',
        'hk-macroFeed': 'Macro feed',
        'hk-split': `Split`,
        'hk-doubleSplit': `Double split`,
        'hk-tripleSplit': `Triple split`,
        'hk-split16': `Split 16`,
        'hk-pause': `Cell pause`,
        'hk-showTop5': `Show/hide team top 5`,
        'hk-showTime': `Show/hide current time`,
        'hk-showSplitRange': `Show/hide split range`,
        'hk-showSplitInd': 'Show/hide split indicators',
        'hk-showTeammatesInd': 'Show/hide teammates indicators',
        'hk-showOppColors': `Show/hide opponents colors`,
        'hk-toggleSkins': 'Toggle skins (custom/default)',
        'hk-showSkins': `Show/hide skins`,
        'hk-transparentSkins': 'Toggle transparent skins',
        'hk-showStats': `Show/hide game stats`,
        'hk-toggleCells': `Toggle own cells (smallest/biggest)`,
        'hk-showFood': `Show/hide food`,
        'hk-showGrid': `Show/hide grid`,
        'hk-showMiniMapGuides': 'Show/hide minimap guides',
        'hk-hideChat': `Show/hide chat`,
        'hk-showHUD': `Show/hide HUD`,
        'hk-copyLb': `Copy leaderboard`,
        'hk-showLb': 'Show/hide leaderboard',
        'hk-toggleAutoZoom': `Toggle auto zoom`,
        'hk-resetZoom': `Reset zoom`,
        'hk-zoomLevel': 'Zoom level',
        'hk-toggleDeath': `Toggle death location`,
        'hk-clearChat': `Show chat history / Clear chat`,
        'hk-showBgSectors': `Show/hide background sectors`,
        'hk-hideBots': `Show/hide small bots`,
        'hk-showNames': 'Show/hide names',
        'hk-hideTeammatesNames': `Show/hide teammates names`,
        'hk-showMass': `Show/hide mass`,
        'hk-showMiniMap': 'Show/hide minimap',
        'hk-chatMessage': `Enter chat message`,
        'hk-quickResp': `Quick respawn`,
        'hk-autoResp': `Toggle auto respawn`,
        'hk-switchServerMode': `Switch server [public/private]`,
        'hk-showTargeting': 'Show/hide targeting panel',
        'hk-setTargeting': `Start/stop targeting (following)`,
        'hk-cancelTargeting': 'Cancel targeting',
        'hk-changeTarget': 'Change target',
        'hk-privateMiniMap': 'Show target on the minimap',
        'hk-showQuest': 'Show/hide quest',
        commands: `Commands`,
        comm1: `Feed me!`,
        comm2: `Split into me!`,
        comm3: 'Need backup at %currentSector%!',
        comm4: 'Enemy spotted at %currentSector%!',
        comm5: `Need a teammate!`,
        comm6: 'Tank the virus!',
        comm7: `Eat the virus!`,
        comm8: `Let's bait!`,
        comm9: `Fake tricksplit!`,
        comm0: `Fuck!`,
        comm10: `Tricksplit!`,
        comm11: `Left!`,
        comm12: `Up!`,
        comm13: 'Right!',
        comm14: 'Bottom!',
        saveComm: 'Save commands',
        theme: `Theme`,
        restoreThemeSettings: `Restore theme`,
        basicTheming: 'Basic theming',
        themePreset: `Theme preset`,
        themeType: 'Theme type',
        darkTheme: 'Dark theme',
        lightTheme: `Light theme`,
        mainColor: 'Main color',
        bgColor: `Background`,
        bordersColor: 'Map borders',
        gridColor: `Grid`,
        sectorsColor: `Sectors font`,
        namesColor: `Names`,
        namesStrokeColor: `Names stroke`,
        massColor: 'Mass',
        massStrokeColor: `Mass stroke`,
        virusColor: `Virus`,
        virusStrokeColor: `Virus stroke`,
        foodColor: `Food`,
        namesFont: 'Names font',
        massFont: `Mass font`,
        sectorsFont: 'Sectors font',
        namesScale: `Names scale`,
        massScale: 'Mass scale',
        virMassScale: 'Virus mass scale',
        strokeScale: `Text stroke scale`,
        foodSize: `Food size`,
        bordersWidth: 'Map borders width',
        sectorsWidth: `Sectors grid width`,
        sectorsFontSize: `Sectors font size`,
        cellsAlpha: `Cells transparency`,
        skinsAlpha: 'Skins transparency',
        virusAlpha: `Virus transparency`,
        textAlpha: `Names & mass transparency`,
        virusStrokeSize: `Virus stroke size`,
        teammatesIndColor: `Teammate indicator`,
        cursorTrackingColor: `Cursor tracking`,
        splitRangeColor: `Split range`,
        safeAreaColor: `Safe area`,
        dangerAreaColor: `Danger area`,
        ghostCellsColor: `Ghost cells`,
        ghostCellsAlpha: 'Ghost cells transparency',
        menuTheming: `Menu`,
        menuPreset: `Menu theme`,
        menuMainColor: `Main color`,
        menuBtnTextColor: `Button text`,
        menuPanelColor: `Panel`,
        menuPanelColor2: `Panel (2)`,
        menuTextColor: 'Panel text',
        menuTextColor2: `Panel text (2)`,
        btn1Color: `Button #1`,
        btn1Color2: `Button #1 (2)`,
        btn2Color: 'Button #2',
        btn2Color2: `Button #2 (2)`,
        btn3Color: `Button #3`,
        btn3Color2: `Button #3 (2)`,
        btn4Color: `Button #4`,
        btn4Color2: `Button #4 (2)`,
        menuBg: 'Panel background image',
        menuOpacity: `Transparency`,
        hudTheming: `HUD`,
        hudMainColor: `Main color`,
        hudColor: 'Background',
        hudTextColor: `Text`,
        statsHudColor: `Stats`,
        timeHudColor: 'Time',
        top5MassColor: `Mass`,
        lbMeColor: `Leaderboard - me`,
        lbTeammateColor: `Leaderboard - teammate`,
        hudFont: `HUD font`,
        hudScale: `HUD scale`,
        chatTheming: `Chat`,
        messageColor: 'Message background',
        messageTextColor: 'Message text',
        messageTimeColor: `Message time`,
        messageNickColor: `Message nick`,
        commandsColor: `Command background`,
        commandsTextColor: 'Command text',
        commandsTimeColor: `Command time`,
        commandsNickColor: `Command nick`,
        chatBoxColor: `Chatbox color`,
        chatScale: `Chat scale`,
        miniMapTheming: `Minimap`,
        miniMapSectorsColor: `Sectors`,
        miniMapSectorColor: `Current sector`,
        miniMapGuidesColor: `Guides`,
        miniMapNickColor: `Nick`,
        miniMapNickStrokeColor: `Nick stroke`,
        miniMapMyCellColor: `My cell`,
        miniMapMyCellStrokeColor: `My cell stroke`,
        miniMapTeammatesColor: `Teammates`,
        miniMapDeathLocationColor: `Death location`,
        miniMapFont: `Minimap font`,
        miniMapNickFont: `Nick font`,
        miniMapWidth: `Minimap width`,
        miniMapSectorsOpacity: `Sectors transparency`,
        miniMapNickSize: 'Nick size',
        miniMapNickStrokeSize: 'Nick stroke size',
        miniMapMyCellSize: `My cell size`,
        miniMapMyCellStrokeSize: `My cell stroke size`,
        miniMapTeammatesSize: 'Teammates size',
        miniMapGhostCellsColor: `Ghost cells`,
        miniMapGhostCellsAlpha: `Ghost cells transparency`,
        imagesTheming: `Graphics / cursors`,
        customBackground: `Custom background image`,
        'customMapTexture': 'Custom map texture',
        'customMapLogo': 'Custom map logo',
        customCursor: `Custom cursor image`,
        hideChatMsgA: `Chat is visible!`,
        hideChatMsgB: `Chat is hidden!`,
        showSkinsMsgA: `Skins are visible!`,
        showSkinsMsgB: `Skins are hidden!`,
        hideSmallBotsMsgA: `Small bots are visible!`,
        hideSmallBotsMsgB: `Small bots are hidden!`,
        autoRespMsgA: `Auto respawn is on!`,
        autoRespMsgB: `Auto respawn is off!`,
        autoZoomMsgA: `Auto zoom is on!`,
        autoZoomMsgB: `Auto zoom is off!`,
        targetNotSet: `Target not set`,
        targetDead: 'Dead',
        targetDistance: 'Distance',
        targetMass: `Mass altogether`,
        totalPartyPlayers: `Active players`,
        totalPartyMass: `Total mass`,
        exportImport: `Export / import settings`,
        exportSettings: 'Export settings',
        exportInfo: 'To export selected settings copy the code below and save it to a text file encoded in Unicode.',
        importSettings: `Import settings`,
        importInfo: `To import selected settings paste an exported code below and press the "Import settings" button.`,
        profile: `Profile`,
        profiles: 'Profiles',
        skins: `Skins`,
        moreSkins: `Add skins`,
        thanks: `Thanks to Awesome!`,
        saveSett: 'Save',
        saved: `Saved!`,
        resetSett: `Reset`,
        close: `Close`,
        enterChatMsg: `Enter chat message`,
        activeParties: `Active parties`,
        noActiveParties: `No active parties ;(`,
        playlist: `Playlist`,
        pause: `PAUSE!`,
        visit: 'Visit',
        exit: 'OGARio by szymy: Are you sure you want to quit the game?',
        blockWarn: `WARNING! Popups are blocked in the settings.`,
        unblockPopups: `Temporary unblock`,
        mass: 'Mass',
        score: `Score`,
        leaderboard: `Leaderboard`,
        leaderboardLength:'Length of Leaderboard (10)',
        user: 'User',
        userMuted: 'User %user% has been muted.',
        userUnmuted: `User %user% has been unmuted.`,
        mute: `Mute`,
        unmute: 'Unmute',
        mutedUsers: `Muted users`,
        activeUsers: `Active users`,
        showActiveUsers: `Show active users`,
        none: `None`,
        sounds: `Sounds`,
        page_menu_main_free_coins: 'Free Coins',
        page_menu_main_gifts: 'Gifts',
        page_menu_main_dailyquests: `Daily Quest`,
        page_shop: `Shop`
    },
    'ru-RU': {
        'start': 'Главная',
        'settings': 'Настройки',
        'restoreSettings': 'Сбросить',
        'animationGroup': 'Анимация',
        'zoomGroup': 'Масштабирование',
        newGroup:'Новое',
        stickyCell:'Прилипание к шару (ПКМ-ЛКМ)',
        'macroFeeding': 'Задержка макро-фида (80мс)',
        'renderQuality':'Качество отрисовки (1)',
        'debug':'Debug',
        'mapLocalFix3':'Запоминать положение карты',
        'mapGlobalFix4':'Вращать карту в правильное положение (Легенд) ',
        'experimental1':'Экспериментальное улучшение №1',
        'cameraDelay':'Задержка камеры (0)',
        zoomSmoothness:'Плавность зума (10)',
        'showExtraMiniMapGuides':'Доп. указатели на миникарте',
        'respGroup': 'Респавн',
        'namesGroup': 'Имена',
        'massGroup': 'Масса',
        'skinsGroup': 'Скины',
        'foodGroup': 'Еда',
        'transparencyGroup': 'Прозрачность / цвета',
        'gridGroup': 'Сетка / секторы',
        'miniMapGroup': 'Миникарта',
        'helpersGroup': 'Подсказки',
        'mouseGroup': 'Управление мышью',
        'hudGroup': 'HUD',
        'chatGroup': 'Чат',
        'statsGroup': 'Статистика',
        'extrasGroup': 'Дополнительно',
        'noSkins': 'Без скинов',
        'noNames': 'Без имен',
        'noColors': 'Без цветов',
        'showMass': 'Показывать массу',
        'skipStats': 'Пропустить статистику после смерти',
        'showQuest': 'Показать квест',
        'autoZoom': 'Авто зум',
        'animation': 'Задержка анимации',
        'zoomSpeedValue': 'Длина шага зума',
        'quickResp': 'Быстрый респавн (по горячей клавише)',
        'autoResp': 'Авто респавн',
        'autoHideCellsInfo': 'Автоскрытие имён и массы',
        'autoHideNames': 'Авто-скрыть имена',
        'autoHideMass': 'Авто-скрыть массу',
        'autoHideFood': 'Авто-скрыть еду (при большой массе)',
        'autoHideFoodOnZoom': 'Авто-скрыть еду (при зуме)',
        'optimizedNames': 'Оптимизировать имена',
        'hideMyName': 'Скрыть мое имя',
        'hideTeammatesNames': 'Скрыть имена товарищей по команде',
        'optimizedMass': 'Оптимизированная масса (+/- 2%)',
        'shortMass': 'Укороченная масса (k)',
        'virMassShots': 'Вирусные выстрелы, счётчик до выстрела',
        'hideMyMass': 'Скрыть мою массу',
        'hideEnemiesMass': 'Скрыть массу врагов',
        'vanillaSkins': 'Агаровские скины',
        'customSkins': 'Кастомные скины',
        'myTransparentSkin': 'Мой скин прозрачный',
        'myCustomColor': 'Мой кастомный цвет',
        'transparentCells': 'Прозрачные клетки',
        'transparentViruses': 'Прозрачные вирусы',
        'transparentSkins': 'Прозрачные скины',
        'showGrid': 'Сетка',
        'showBgSectors': 'Сектора',
        'showMapBorders': 'Границы карты',
        'showGhostCells': 'Призрачные клетки',
        'showMiniMap': 'Показать миникарту',///
        'showMiniMapGrid': 'Показать сетку миникарты',
        'showMiniMapGuides': 'Показать мини-карты',
        'showMiniMapGhostCells': 'Показать призрачные клетки',
        'oneColoredTeammates': 'Одноцветные товарищи по команде',
        'optimizedFood': 'Оптимизированная еда',
        'rainbowFood': 'Разноцветная еда',
        'oppColors': 'Цвета противников',
        'oppRings': 'Кольца противников',
        'virColors': 'Цвет вирусов',
        'splitRange': 'Радиус дальности сплита',
        'virusesRange': 'Диапазон вирусов',
        'textStroke': 'Обводка текста',
        'namesStroke': 'Обводка имени',
        'massStroke': 'Обводка массы',
        'cursorTracking': 'Линии к курсору',
        'teammatesInd': 'Показатели товарищей по команде',
        'mouseSplit': 'ЛКМ - Сплит мышкой',
        'mouseFeed': 'ПКМ - Кормить мышкой',
        'mouseInvert': 'Поменять местами ПКМ и ЛКМ',
        'disableChat': 'Отключить чат',
        'hideChat': 'Скрыть чат',
        'chatSounds': 'Звуки чата',
        'chatEmoticons': 'Смайлы',
        'showChatImages': 'Картинки',
        'showChatVideos': 'Видео',
        'showChatBox': 'Чатбокс вместо уведомлений',
        'messageSound': 'Звук сообщений',
        'commandSound': 'Звук команд',
        'virusSounds': 'Звук выстрела вируса',
         virusSoundURL:'Звук выстрела вируса URL',
        'showTop5': 'Показать топ 5 команды',
        showTop5Sectors:'Показать сектора в топ 5',
        'showTargeting': 'Показать таргетинг',
        'showTime': 'Показать текущее время',
        'showLbData': 'Показать массу в LEADERBOARD',
        'normalLb': 'Заголовок \ "LEADERBOARD \"',
        'centeredLb': 'По-центру LEADERBOARD',
        'fpsAtTop': 'FPS сверху',
        'showStats': 'Показывать строку статистики',
        'showStatsMass': 'Текущая масса',
        'showStatsSTE': 'STE: Максимально набрано',
        'showStatsN16': 'Количество шаров n / 16',
        'showStatsFPS': 'FPS - кадры в секунду',
        'showStatsPPS': 'PPS - пакеты в секунду',
        'blockPopups': 'Блокировать всплывающие окна (реклама / магазин / квест)',
        'hotkeys': 'Клавиатура',
        'hk-switchPlayer':'Сменить игрока',
        'hk-inst-assign': 'Чтобы назначить горячую клавишу, нажмите на поле ввода и нажмите выбранную клавишу.',
        'hk-inst-delete': 'Чтобы удалить горячую клавишу, нажмите на поле ввода и нажмите клавишу DELETE.',
        'hk-inst-keys': 'Возможные комбинации клавиш с клавишами CTRL и ALT.',
        'hk-feed': 'Кормить',
        'hk-macroFeed': 'Быстро кормить',
        'hk-split': 'Сплит',
        'hk-doubleSplit': 'Двойной сплит',
        'hk-tripleSplit': `Тройной сплит`,
        'hk-split16': 'Сплит на 16',
        'hk-pause': 'Пауза',
        'hk-showTop5': 'Показать / скрыть топ товарищей',
        'hk-showTime': 'Показать / скрыть текущее время',
        'hk-showSplitRange': 'Показать / скрыть радиус дальности сплита',
        'hk-showSplitInd': 'Показать / скрыть индикатор сплитов',
        'hk-showTeammatesInd': 'Показать / скрыть показатели товарищей по команде',
        'hk-showOppColors': 'Показать / скрыть цвета противников',
        'hk-toggleSkins': 'Переключить скины (пользовательские / по умолчанию)',
        'hk-showSkins': 'Показать / скрыть скины',
        'hk-transparentSkins': 'Переключить прозрачные скины',
        'hk-showStats': 'Показать / скрыть игровую статистику',
        'hk-toggleCells': 'Переключить собственные ячейки (самые маленькие / самые большие)',
        'hk-showFood': 'Показать / скрыть еду',
        'hk-showGrid': 'Показать / скрыть сетку',
        'hk-showMiniMapGuides': 'Показать / скрыть направляющие миникарты',
        'hk-hideChat': 'Показать / скрыть чат',
        'hk-showHUD': 'Показать / скрыть HUD',
        'hk-copyLb': 'Копировать список лидеров',
        'hk-showLb': 'Показать / скрыть таблицу лидеров',
        'hk-toggleAutoZoom': 'Переключить автоматический зум',
        'hk-resetZoom': 'Сбросить масштаб',
        'hk-zoomLevel': 'Уровень масштабирования',
        'hk-toggleDeath': 'Переключить место смерти',
        'hk-clearChat': 'Показать историю чата / Очистить чат',
        'hk-showBgSectors': 'Показать / скрыть фоновые сектора',
        'hk-hideBots': 'Показать / скрыть маленьких ботов',
        'hk-showNames': 'Показать / скрыть имена',
        'hk-hideTeammatesNames': 'Показать / скрыть имена товарищей по команде',
        'hk-showMass': 'Показать / скрыть массу',
        'hk-showMiniMap': 'Показать / скрыть миникарту',
        'hk-chatMessage': 'Введите сообщение чата',
        'hk-quickResp': 'Быстрое возрождение',
        'hk-autoResp': 'Переключить авто респаун',
        'hk-switchServerMode': 'Переключить сервер [публичный / частный]',
        'hk-showTargeting': 'Показать / скрыть панель таргетинга',
        'hk-setTargeting': 'Начать / остановить таргетинг (следующий)',
        'hk-cancelTargeting': 'Отмена таргетинга',
        'hk-changeTarget': 'Изменить цель',
        'hk-privateMiniMap': 'Показать цель на миникарте',
        'hk-showQuest': 'Показать / спрятать квест',
        'commands': 'Команды',
        'comm1': 'Feed me!',
        'comm2': 'Split into me!',
        'comm3': 'Need backup at %currentSector%!',
        'comm4': 'Enemy spotted at %currentSector%!',
        'comm5': 'Need a teammate!',
        'comm6': 'Tank the virus!',
        'comm7': 'Eat the virus!',
        'comm8': 'Let\'s bait!',
        'comm9': 'Fake tricksplit!',
        'comm0': 'Fuck!',
        'comm10': 'Tricksplit!',
        'comm11': 'Left!',
        'comm12': 'Up!',
        'comm13': 'Right!',
        'comm14': 'Bottom!',
        'saveComm': 'Сохранить команды',
        'theme': 'Тема',
        'restoreThemeSettings': 'Сброс темы',
        'basicTheming': 'Основная тема',
        'themePreset': 'Предустановленые темы игры',
        'themeType': 'Тип темы',
        'darkTheme': 'Темная тема',
        'lightTheme': 'Светлая тема',
        'mainColor': 'Основной цвет',
        'bgColor': 'Фон',
        'bordersColor': 'Границы карты',
        'gridColor': 'Сетка',
        'sectorsColor': 'Цвет секторов',
        'namesColor': 'Имена',
        'namesStrokeColor': 'Обводка имен',
        'massColor': 'Масса',
        'massStrokeColor': 'Обводка массы',
        'virusColor': 'Вирус',
        'virusStrokeColor': 'Обводка вируска',
        'foodColor': 'Еда',
        'namesFont': 'Шрифт имени',
        'massFont': 'Шрифт массы',
        'sectorsFont': 'Шрифт секторов',
        'namesScale': 'Размер имен',
        'massScale': 'Размер массы',
        'virMassScale': 'Размер массы вирусов',
        'strokeScale': 'Толщина обводки',
        'foodSize': 'Размер еды',
        'bordersWidth': 'Ширина границ карты',
        'sectorsWidth': 'Ширина секторов карты',
        'sectorsFontSize': 'Размер шрифта секторов',
        'cellsAlpha': 'Прозрачность шаров',
        'skinsAlpha': 'Прозрачность скинов',
        'virusAlpha': 'Прозрачность вирусов',
        'textAlpha': 'Прозрачность имен и массы',
        'virusStrokeSize': 'Толщина обводки вируса',
        'teammatesIndColor': 'Индикатор товарища',
        'cursorTrackingColor': 'Линии курсора',
        'splitRangeColor': 'Радиус сплита',
        'safeAreaColor': 'Безопасная зона',
        'dangerAreaColor': 'Опасная Зона',
        'ghostCellsColor': 'Привидения игроков',
        'ghostCellsAlpha': 'Прозрачность привидений игроков',
        'menuTheming': 'Меню',
        'menuPreset': 'Предустановленые стили меню',
        'menuMainColor': 'Основной цвет',
        'menuBtnTextColor': 'Button text',
        'menuPanelColor': 'Panel',
        'menuPanelColor2': 'Panel (2)',
        'menuTextColor': 'Panel text',
        'menuTextColor2': 'Panel text (2)',
        'btn1Color': 'Button #1',
        'btn1Color2': 'Button #1 (2)',
        'btn2Color': 'Button #2',
        'btn2Color2': 'Button #2 (2)',
        'btn3Color': 'Button #3',
        'btn3Color2': 'Button #3 (2)',
        'btn4Color': 'Button #4',
        'btn4Color2': 'Button #4 (2)',
        'menuBg': 'Фоновая картинка',
        'menuOpacity': 'Прозрачность',
        'hudTheming': 'HUD',
        'hudMainColor': 'Основной цвет HUD',
        'hudColor': 'Фон HUD',
        'hudTextColor': 'Текст',
        'statsHudColor': 'Статы',
        'timeHudColor': 'Время',
        'top5MassColor': 'Масса',
        'lbMeColor': 'Я в топе',
        'lbTeammateColor': 'Товарищ в топе',
        'hudFont': 'HUD шрифт',
        'hudScale': 'HUD размер',
        'chatTheming': 'Чат',
        'messageColor': 'Фон сообщения',
        'messageTextColor': 'Текст сообщения',
        'messageTimeColor': 'Время сообщения',
        'messageNickColor': 'Ник в сообщении',
        'commandsColor': 'Фон команды',
        'commandsTextColor': 'Текст  команды',
        'commandsTimeColor': 'Время  команды',
        'commandsNickColor': 'Ник в  команде',
        'chatBoxColor': 'Цвет чатбокса',
        'chatScale': 'Размер чата',
        'miniMapTheming': 'Миникарта',
        'miniMapSectorsColor': 'Сектора',
        'miniMapSectorColor': 'Текущий сектор',
        'miniMapGuidesColor': 'Оси X/Y',
        'miniMapNickColor': 'Ник',
        'miniMapNickStrokeColor': 'Обводка ника',
        'miniMapMyCellColor': 'Мой шар',
        'miniMapMyCellStrokeColor': 'Обводка моего шара',
        'miniMapTeammatesColor': 'Товарищи',
        'miniMapDeathLocationColor': 'Место смерти',
        'miniMapFont': 'Шрифт миникарты',
        'miniMapNickFont': 'Шрифт ника',
        'miniMapWidth': 'Ширина миникарты',
        'miniMapSectorsOpacity': 'Прозрачность секторов',
        'miniMapNickSize': 'Размер ника',
        'miniMapNickStrokeSize': 'Толщина обводки ника',
        'miniMapMyCellSize': 'Размер моего шара',
        'miniMapMyCellStrokeSize': 'Толщина обводки моего шара',
        'miniMapTeammatesSize': 'Размер товарищей',
        'miniMapGhostCellsColor': 'Цвет привидений',
        'miniMapGhostCellsAlpha': 'Прозрачность привидений',
        'imagesTheming': 'Graphics / cursors',
        'customBackground': 'Картинка Фон карты',
        'customMapTexture': 'Картинка Текстура карты',
        'customMapLogo': 'Картинка Лого карты',
        'customCursor': 'Custom cursor image',
        'hideChatMsgA': 'Chat is visible!',
        'hideChatMsgB': 'Chat is hidden!',
        'showSkinsMsgA': 'Skins are visible!',
        'showSkinsMsgB': 'Skins are hidden!',
        'hideSmallBotsMsgA': 'Small bots are visible!',
        'hideSmallBotsMsgB': 'Small bots are hidden!',
        'autoRespMsgA': 'Auto respawn is on!',
        'autoRespMsgB': 'Auto respawn is off!',
        'autoZoomMsgA': 'Auto zoom is on!',
        'autoZoomMsgB': 'Auto zoom is off!',
        'targetNotSet': 'Target not set',
        'targetDead': 'Dead',
        'targetDistance': 'Distance',
        'targetMass': 'Mass altogether',
        'totalPartyPlayers': 'Active players',
        'totalPartyMass': 'Total mass',
        'exportImport': 'Export / import settings',
        'exportSettings': 'Export settings',
        'exportInfo': 'To export selected settings copy the code below and save it to a text file encoded in Unicode.',
        'importSettings': 'Import settings',
        'importInfo': 'To import selected settings paste an exported code below and press the \"Import settings\" button.',
        'profile': 'Профиль',
        'profiles': 'Профили',
        'skins': 'Skins',
        'moreSkins': 'Add skins',
        'thanks': 'Thanks to Awesome!',
        'saveSett': 'Сохранить',
        'saved': 'Сохранено!',
        'resetSett': 'Сбросить',
        'close': 'Close',
        'enterChatMsg': 'Enter chat message',
        'activeParties': 'Active parties',
        'noActiveParties': 'No active parties ;(',
        'playlist': 'Playlist',
        'pause': 'ПАУЗА!',
        'visit': 'Сайт данного мода',
        'exit': 'Вы уверены что хотите покинуть игру?',
        'blockWarn': 'WARNING! Popups are blocked in the settings.',
        'unblockPopups': 'Temporary unblock',
        'mass': 'Mass',
        'score': 'Score',
        'leaderboard': 'Leaderboard',
        'leaderboardLength':'Количество в Leaderboard (10)',
        'user': 'Пользователь',
        'userMuted': 'Пользователь %user% теперь заглушен.',
        'userUnmuted': 'Пользователь %user% снова виден.',
        'mute': 'Заглушить',
        'unmute': 'Видеть',
        'mutedUsers': 'Заглушенные пользователи',
        'activeUsers': 'Активные пользователи',
        'showActiveUsers': 'показать активных пользователей',
        'none': 'Нет',
        'sounds': 'Звуки',
        'page_menu_main_free_coins': 'Бесплатные монеты',
        'page_menu_main_gifts': 'Подарки',
        'page_menu_main_dailyquests': 'Квест дня',
        'page_shop': 'Магазин'
    }
};
let lang = 'en';
displayText['ru'] = displayText['ru-RU'] 
displayText['uk'] = displayText['ru-RU'] 
const userLanguage = window.navigator.language || window.navigator.userLanguage;
if (userLanguage && displayText.hasOwnProperty(userLanguage)) {
    lang = userLanguage;
}
const textLanguage = displayText[lang];


const theme = {
    preset: `ogario-v3`,
    darkTheme: true,
    mainColor: '#01d9cc',
    bgColor: `#000a11`,
    bordersColor: `#01d9cc`,
    gridColor: '#00243e',
    sectorsColor: `#00243e`,
    namesColor: `#ffffff`,
    namesStrokeColor: `#000000`,
    massColor: `#ffffff`,
    massStrokeColor: `#000000`,
    virusColor: `#002f52`,
    virusStrokeColor: '#00b9e8',
    foodColor: '#5000ff',
    teammatesIndColor: `#ffffff`,
    cursorTrackingColor: `#ffffff`,
    splitRangeColor: `#ffffff`,
    ghostCellsColor: `#ffffff`,
    safeAreaColor: `#ffffff`,
    dangerAreaColor: `#bf00aa`,
    namesFont: `ubuntu-bold`,
    namesFontFamily: `Ubuntu`,
    namesFontWeight: 700,
    massFont: 'ubuntu-bold',
    massFontFamily: `Ubuntu`,
    massFontWeight: 700,
    sectorsFont: `ubuntu`,
    sectorsFontFamily: `Ubuntu`,
    sectorsFontWeight: 400,
    sectorsX: 5,
    sectorsY: 5,
    namesScale: 1,
    massScale: 3,
    virMassScale: 3,
    strokeScale: 1,
    foodSize: 5,
    bordersWidth: 40,
    sectorsWidth: 40,
    sectorsFontSize: 1200,
    cellsAlpha: 0.9,
    skinsAlpha: 0.7,
    virusAlpha: 0.6,
    textAlpha: 1,
    ghostCellsAlpha: 0.3,
    virusStrokeSize: 14,
    menuPreset: `ogario-v3`,
    menuMainColor: `#01d9cc`,
    menuBtnTextColor: `#ffffff`,
    menuPanelColor: '#00243e',
    menuPanelColor2: `#002f52`,
    menuTextColor: '#ffffff',
    menuTextColor2: `#8096a7`,
    btn1Color: `#018cf6`,
    btn1Color2: '#0176ce',
    btn2Color: '#00b9e8',
    btn2Color2: `#0099c0`,
    btn3Color: `#8d5fe6`,
    btn3Color2: '#814ee3',
    btn4Color: '#bf00aa',
    btn4Color2: '#a80096',
    menuBg: `https://cdn.ogario.ovh/static/img/pattern.png`,
    menuOpacity: 0.96,
    hudMainColor: `#01d9cc`,
    hudColor: 'rgba(0,0,0,0.4)',
    hudTextColor: '#ffffff',
    statsHudColor: `#ffffff`,
    timeHudColor: `#01d9cc`,
    top5MassColor: `#bf00aa`,
    lbMeColor: '#bf00aa',
    lbTeammateColor: `#018cf6`,
    hudFont: `ubuntu-bold`,
    hudFontFamily: `Ubuntu`,
    hudFontWeight: 700,
    hudScale: 1,
    messageColor: `rgba(0,0,0,0.4)`,
    messageTextColor: `#ffffff`,
    messageTimeColor: `#018cf6`,
    messageNickColor: '#01d9cc',
    commandsColor: `rgba(191,0,170,0.9)`,
    commandsTextColor: `#ffffff`,
    commandsTimeColor: '#bf00aa',
    commandsNickColor: `#ffffff`,
    chatBoxColor: `rgba(0,0,0,0.4)`,
    chatScale: 1,
    miniMapSectorsColor: `#ffffff`,
    miniMapSectorColor: `#01d9cc`,
    miniMapGuidesColor: '#bf00aa',
    miniMapNickColor: '#ffffff',
    miniMapNickStrokeColor: `#000000`,
    miniMapMyCellColor: `#ffffff`,
    miniMapMyCellStrokeColor: `#bf00aa`,
    miniMapTeammatesColor: `#01d9cc`,
    miniMapDeathLocationColor: `#bf00aa`,
    miniMapGhostCellsColor: `#ffffff`,
    miniMapFont: `ubuntu-bold`,
    miniMapFontFamily: 'Ubuntu',
    miniMapFontWeight: 700,
    miniMapNickFont: `ubuntu-bold`,
    miniMapNickFontFamily: `Ubuntu`,
    miniMapNickFontWeight: 700,
    miniMapWidth: 240,
    miniMapTop: 0,//24,
    miniMapSectorsOpacity: 0.1,
    miniMapNickSize: 11,
    miniMapNickStrokeSize: 2,
    miniMapMyCellSize: 7.5,
    miniMapMyCellStrokeSize: 4,
    miniMapTeammatesSize: 5.5,
    miniMapGhostCellsAlpha: 0.15,
    customBackground: '',
    customMapTexture:'',
    customMapLogo:'https://i.imgur.com/7cugADY.png',
    customCursor: 'https://cdn.ogario.ovh/static/img/cursors/cursor_02.cur'
};

const themePresets = {
    'ogario-v3': {
        name: `OGARio v3`,
        darkTheme: true,
        mainColor: '#01d9cc',
        bgColor: '#000a11',
        bordersColor: `#01d9cc`,
        gridColor: `#00243e`,
        sectorsColor: `#00243e`,
        namesColor: '#ffffff',
        namesStrokeColor: `#000000`,
        massColor: `#ffffff`,
        massStrokeColor: '#000000',
        virusColor: `#002f52`,
        virusStrokeColor: `#00b9e8`,
        foodColor: `#5000ff`,
        teammatesIndColor: `#ffffff`,
        cursorTrackingColor: `#ffffff`,
        splitRangeColor: `#ffffff`,
        safeAreaColor: `#ffffff`,
        dangerAreaColor: `#bf00aa`,
        namesFont: 'ubuntu-bold',
        massFont: `ubuntu-bold`,
        sectorsFont: 'ubuntu',
        namesScale: 1,
        massScale: 3,
        foodSize: 5,
        bordersWidth: 40,
        sectorsWidth: 40,
        sectorsFontSize: 1200,
        cellsAlpha: 0.9,
        skinsAlpha: 0.7,
        virusAlpha: 0.6,
        textAlpha: 1,
        virusStrokeSize: 14,
        menuPreset: `ogario-v3`,
        menuMainColor: `#01d9cc`,
        menuBtnTextColor: `#ffffff`,
        menuPanelColor: `#00243e`,
        menuPanelColor2: '#002f52',
        menuTextColor: `#ffffff`,
        menuTextColor2: `#8096a7`,
        btn1Color: `#018cf6`,
        btn1Color2: '#0176ce',
        btn2Color: `#00b9e8`,
        btn2Color2: `#0099c0`,
        btn3Color: '#8d5fe6',
        btn3Color2: `#814ee3`,
        btn4Color: `#bf00aa`,
        btn4Color2: '#a80096',
        menuBg: `https://cdn.ogario.ovh/static/img/pattern.png`,
        menuOpacity: 0.96,
        hudMainColor: `#01d9cc`,
        hudColor: `rgba(0,0,0,0.4)`,
        hudTextColor: `#ffffff`,
        statsHudColor: `#ffffff`,
        timeHudColor: `#01d9cc`,
        top5MassColor: '#bf00aa',
        lbMeColor: '#bf00aa',
        lbTeammateColor: `#018cf6`,
        hudFont: 'ubuntu-bold',
        hudScale: 1,
        messageColor: `rgba(0,0,0,0.4)`,
        messageTextColor: `#ffffff`,
        messageTimeColor: '#018cf6',
        messageNickColor: `#01d9cc`,
        commandsColor: 'rgba(191,0,170,0.9)',
        commandsTextColor: `#ffffff`,
        commandsTimeColor: `#bf00aa`,
        commandsNickColor: `#ffffff`,
        chatBoxColor: 'rgba(0,0,0,0.4)',
        chatScale: 1,
        miniMapSectorsColor: '#ffffff',
        miniMapSectorColor: `#01d9cc`,
        miniMapGuidesColor: `#bf00aa`,
        miniMapNickColor: `#ffffff`,
        miniMapNickStrokeColor: '#000000',
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: `#bf00aa`,
        miniMapTeammatesColor: `#01d9cc`,
        miniMapDeathLocationColor: `#bf00aa`,
        miniMapFont: `ubuntu-bold`,
        miniMapNickFont: `ubuntu-bold`,
        miniMapWidth: 240,
        miniMapSectorsOpacity: 0.1,
        miniMapNickSize: 11,
        miniMapNickStrokeSize: 2,
        miniMapMyCellSize: 7.5,
        miniMapMyCellStrokeSize: 4,
        miniMapTeammatesSize: 5.5,
        customBackground: '',
        'customMapTexture': '',
        customCursor: `https://cdn.ogario.ovh/static/img/cursors/cursor_02.cur`
    },
    'masscare':{"name":"Masscare (dark)","darkTheme":true,"mainColor":"#651fff","bgColor":"#000000","bordersColor":"#ffffff","gridColor":"#0a0a0a","sectorsColor":"#0a0a0a","namesColor":"#ffffff","namesStrokeColor":"#000000","massColor":"#ffffff","massStrokeColor":"#000000","virusColor":"#000000","virusStrokeColor":"#ffffff","foodColor":"#002a80","teammatesIndColor":"#ffffff","cursorTrackingColor":"#ffffff","splitRangeColor":"#ffffff","ghostCellsColor":"#ffffff","safeAreaColor":"#ffffff","dangerAreaColor":"#ffffff","namesFont":"ubuntu","namesFontFamily":"Ubuntu","namesFontWeight":400,"massFont":"ubuntu","massFontFamily":"Ubuntu","massFontWeight":400,"sectorsFont":"ubuntu","sectorsFontFamily":"Ubuntu","sectorsFontWeight":400,"sectorsX":5,"sectorsY":5,"namesScale":0.5,"massScale":1,"virMassScale":3,"strokeScale":1,"foodSize":1,"bordersWidth":40,"sectorsWidth":40,"sectorsFontSize":900,"cellsAlpha":0.9,"skinsAlpha":0.99,"virusAlpha":0.6,"textAlpha":1,"ghostCellsAlpha":0.3,"virusStrokeSize":14,"menuPreset":"agario","menuMainColor":"#c880ff","menuBtnTextColor":"#ffffff","menuPanelColor":"#0a0a0a","menuPanelColor2":"#0a0a0a","menuTextColor":"#ffffff","menuTextColor2":"#ffffff","btn1Color":"#0a0a0a","btn1Color2":"#0a0a0a","btn2Color":"#0a0a0a","btn2Color2":"#0a0a0a","btn3Color":"#0a0a0a","btn3Color2":"#0a0a0a","btn4Color":"#0a0a0a","btn4Color2":"#0a0a0a","menuBg":"https://i.imgur.com/HMy2hry.png","menuOpacity":1,"hudMainColor":"#000000","hudColor":"rgba(0,0,0,0)","hudTextColor":"#ffffff","statsHudColor":"#ffffff","timeHudColor":"#ff80cc","top5MassColor":"#f380ff","lbMeColor":"#80ffff","lbTeammateColor":"#80ffff","hudFont":"ubuntu","hudFontFamily":"Ubuntu","hudFontWeight":400,"hudScale":1,"messageColor":"rgba(0,0,0,0)","messageTextColor":"#ffffff","messageTimeColor":"#262626","messageNickColor":"#c880ff","commandsColor":"rgba(0,0,0,0)","commandsTextColor":"#ffffff","commandsTimeColor":"#262626","commandsNickColor":"#c880ff","chatBoxColor":"rgba(0,0,0,0)","chatScale":1,"miniMapSectorsColor":"#ffffff","miniMapSectorColor":"#000000","miniMapGuidesColor":"#f380ff","miniMapNickColor":"#ffffff","miniMapNickStrokeColor":"#000000","miniMapMyCellColor":"#f380ff","miniMapMyCellStrokeColor":"#f380ff","miniMapTeammatesColor":"#ff80cc","miniMapDeathLocationColor":"#ff80cc","miniMapGhostCellsColor":"#ffffff","miniMapFont":"ubuntu","miniMapFontFamily":"Ubuntu","miniMapFontWeight":400,"miniMapNickFont":"ubuntu","miniMapNickFontFamily":"Ubuntu","miniMapNickFontWeight":400,"miniMapWidth":200,"miniMapTop":0,"miniMapSectorsOpacity":0.15,"miniMapNickSize":9,"miniMapNickStrokeSize":0,"miniMapMyCellSize":4.5,"miniMapMyCellStrokeSize":0,"miniMapTeammatesSize":4.5,"miniMapGhostCellsAlpha":0.05,"customBackground":"","customMapTexture":"","customMapLogo":"","customCursor":""},
    'ogario-orange': {
        name: `OGARio v2`,
        darkTheme: true,
        mainColor: `#ff7800`,
        bgColor: `#111111`,
        bordersColor: `#ff7800`,
        gridColor: '#292929',
        sectorsColor: `#292929`,
        namesColor: '#ffffff',
        namesStrokeColor: `#000000`,
        massColor: `#ffffff`,
        massStrokeColor: '#000000',
        virusColor: `#666666`,
        virusStrokeColor: `#666666`,
        foodColor: `#e16400`,
        hudMainColor: '#ff7800',
        statsHudColor: `#ff7800`,
        top5MassColor: `#ff7800`,
        timeHudColor: `#ff7800`,
        messageNickColor: `#ff7800`,
        commandsColor: `rgba(255,120,0,0.9)`,
        commandsTimeColor: `#ff7800`,
        commandsTextColor: `#ffffff`,
        miniMapSectorsColor: `#ffffff`,
        miniMapSectorColor: `#ff7800`,
        miniMapGuidesColor: `#ff7800`,
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: `#ff7800`,
        miniMapTeammatesColor: '#ff7800',
        miniMapDeathLocationColor: `#ff7800`,
        miniMapSectorsOpacity: 0.1
    },
    'ogario-gold': {
        name: `OGARio LE`,
        darkTheme: true,
        mainColor: `#b5a642`,
        bgColor: `#000000`,
        bordersColor: `#b5a642`,
        gridColor: `#111111`,
        sectorsColor: `#111111`,
        namesColor: '#ffffff',
        namesStrokeColor: `#000000`,
        massColor: `#ffffff`,
        massStrokeColor: '#000000',
        virusColor: `#666666`,
        virusStrokeColor: '#666666',
        foodColor: `#998c36`,
        hudMainColor: '#b5a642',
        statsHudColor: `#b5a642`,
        top5MassColor: `#b5a642`,
        timeHudColor: '#b5a642',
        messageNickColor: '#b5a642',
        commandsColor: 'rgba(181,166,66,0.9)',
        commandsTimeColor: `#b5a642`,
        commandsTextColor: `#ffffff`,
        miniMapSectorsColor: `#ffffff`,
        miniMapSectorColor: `#b5a642`,
        miniMapGuidesColor: `#b5a642`,
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: `#b5a642`,
        miniMapTeammatesColor: `#b5a642`,
        miniMapDeathLocationColor: `#b5a642`,
        miniMapSectorsOpacity: 0.1
    },
    'ref-style': {
        name: "ReF's Style",
        bgColor: "#000000",
        bordersColor: "#0074fc",
        bordersWidth: 80,
        btn1Color: "#0074fc",
        btn1Color2: "#3592ff",
        btn2Color: "#3592ff",
        btn2Color2: "#3592ff",
        btn3Color: "#3592ff",
        btn3Color2: "#3592ff",
        btn4Color: "#3592ff",
        btn4Color2: "#3592ff",
        cellsAlpha: 0.99,
        chatBoxColor: "rgba(0,0,0,0.4)",
        chatScale: 1,
        commandsColor: "rgba(0,116,252,1)",
        commandsNickColor: "#ffffff",
        commandsTextColor: "#ffffff",
        commandsTimeColor: "#000000",
        cursorTrackingColor: "#ffffff",
        customBackground: "",
        customCursor: "",
        dangerAreaColor: "#0074fc",
        darkTheme: true,
        foodColor: "#0074fc",
        foodSize: 1,
        ghostCellsAlpha: 0.3,
        ghostCellsColor: "#ffffff",
        gridColor: "#0094ff",
        hudColor: "rgba(0,0,0,0.49)",
        hudFont: "ubuntu-bold",
        hudFontFamily: "Ubuntu",
        hudFontWeight: 700,
        hudMainColor: "#0074fc",
        hudScale: 1.15,
        hudTextColor: "#ffffff",
        lbMeColor: "#0074fc",
        lbTeammateColor: "#0074fc",
        mainColor: "#01d9cc",
        massColor: "#ffffff",
        massFont: "ubuntu-bold",
        massFontFamily: "Ubuntu",
        massFontWeight: 700,
        massScale: 0.9,
        massStrokeColor: "#000000",
        menuBg: "",
        menuBtnTextColor: "#ffffff",
        menuMainColor: "#0074fc",
        menuOpacity: 1,
        menuPanelColor: "#050008",
        menuPanelColor2: "#1d0526",
        menuPreset: "ogario-v3",
        menuTextColor: "#ffffff",
        menuTextColor2: "#65458f",
        messageColor: "rgba(0,0,0,0.4)",
        messageNickColor: "#0074fc",
        messageTextColor: "#e8e8e8",
        messageTimeColor: "#545454",
        miniMapDeathLocationColor: "#2b2b2b",
        miniMapFont: "ubuntu-bold",
        miniMapFontFamily: "Ubuntu",
        miniMapFontWeight: 700,
        miniMapGhostCellsAlpha: 0.15,
        miniMapGhostCellsColor: "#ffffff",
        miniMapGuidesColor: "#ff00a8",
        miniMapMyCellColor: "#f0ff3d",
        miniMapMyCellSize: 5,
        miniMapMyCellStrokeColor: "#acba07",
        miniMapMyCellStrokeSize: 0,
        miniMapNickColor: "#ffffff",
        miniMapNickFont: "ubuntu-bold",
        miniMapNickFontFamily: "Ubuntu",
        miniMapNickFontWeight: 700,
        miniMapNickSize: 9,
        miniMapNickStrokeColor: "#4d4d4d",
        miniMapNickStrokeSize: 0,
        miniMapSectorColor: "#000000",
        miniMapSectorsColor: "#ffffff",
        miniMapSectorsOpacity: 0.1,
        miniMapTeammatesColor: "#305eff",
        miniMapTeammatesSize: 5,
        miniMapTop: 25,
        miniMapWidth: 250,
        namesColor: "#ffffff",
        namesFont: "ubuntu-bold",
        namesFontFamily: "Ubuntu",
        namesFontWeight: 700,
        namesScale: 0.9,
        namesStrokeColor: "#000000",
        safeAreaColor: "#ffffff",
        sectorsColor: "#0074fc",
        sectorsFont: "ubuntu",
        sectorsFontFamily: "Ubuntu",
        sectorsFontSize: 940,
        sectorsFontWeight: 400,
        sectorsWidth: 6,
        sectorsX: 5,
        sectorsY: 5,
        skinsAlpha: 0.7,
        splitRangeColor: "#ffffff",
        statsHudColor: "#ffffff",
        strokeScale: 1,
        teammatesIndColor: "#ffffff",
        textAlpha: 1,
        timeHudColor: "#0074fc",
        top5MassColor: "#0074fc",
        virMassScale: 2,
        virusAlpha: 0.4,
        virusColor: "#3b3b3b",
        virusStrokeColor: "#ffffff",
        virusStrokeSize: 10,
        customBackground: '',
        customCursor: ``
    },
    'turbo-style': {
        name: "Turbo's Style",
        bgColor: "#000000",
        bordersColor: "#ff2b77",
        bordersWidth: 80,
        btn1Color: "#ff2b77",
        btn1Color2: "#ff005b",
        btn2Color: "#ff2b77",
        btn2Color2: "#ff005b",
        btn3Color: "#ff2b77",
        btn3Color2: "#ff005b",
        btn4Color: "#ff2b77",
        btn4Color2: "#ff005b",
        cellsAlpha: 0.99,
        chatBoxColor: "rgba(0,0,0,0.4)",
        chatScale: 1,
        commandsColor: "rgba(255,43,119,1)",
        commandsNickColor: "#ffffff",
        commandsTextColor: "#ffffff",
        commandsTimeColor: "#000000",
        cursorTrackingColor: "#ffffff",
        customBackground: "",
        customCursor: "",
        dangerAreaColor: "#ff2b77",
        darkTheme: true,
        foodColor: "#ff2b77",
        foodSize: 1,
        ghostCellsAlpha: 0.3,
        ghostCellsColor: "#ffffff",
        gridColor: "#ff2b77",
        hudColor: "rgba(0,0,0,0.49)",
        hudFont: "ubuntu-bold",
        hudFontFamily: "Ubuntu",
        hudFontWeight: 700,
        hudMainColor: "#ff2b77",
        hudScale: 1.15,
        hudTextColor: "#ffffff",
        lbMeColor: "#ff2b77",
        lbTeammateColor: "#ff2b77",
        mainColor: "#ff2b77",
        massColor: "#000000",
        massFont: "ubuntu-bold",
        massFontFamily: "Ubuntu",
        massFontWeight: 700,
        massScale: 0.9,
        massStrokeColor: "#ffffff",
        menuBg: "",
        menuBtnTextColor: "#ffffff",
        menuMainColor: "#ff2b77",
        menuOpacity: 1,
        menuPanelColor: "#23192c",
        menuPanelColor2: "#382946",
        menuPreset: "ogario-v3",
        menuTextColor: "#ffffff",
        menuTextColor2: "#65458f",
        messageColor: "rgba(0,0,0,0.4)",
        messageNickColor: "#ff2b77",
        messageTextColor: "#e8e8e8",
        messageTimeColor: "#545454",
        miniMapDeathLocationColor: "#2b2b2b",
        miniMapFont: "ubuntu-bold",
        miniMapFontFamily: "Ubuntu",
        miniMapFontWeight: 700,
        miniMapGhostCellsAlpha: 0.15,
        miniMapGhostCellsColor: "#ffffff",
        miniMapGuidesColor: "#ff2b77",
        miniMapMyCellColor: "#ffdd56",
        miniMapMyCellSize: 5,
        miniMapMyCellStrokeColor: "#ff9a6b",
        miniMapMyCellStrokeSize: 0,
        miniMapNickColor: "#ffffff",
        miniMapNickFont: "ubuntu-bold",
        miniMapNickFontFamily: "Ubuntu",
        miniMapNickFontWeight: 700,
        miniMapNickSize: 9,
        miniMapNickStrokeColor: "#4d4d4d",
        miniMapNickStrokeSize: 0,
        miniMapSectorColor: "#000000",
        miniMapSectorsColor: "#ffffff",
        miniMapSectorsOpacity: 0.1,
        miniMapTeammatesColor: "#ff005b",
        miniMapTeammatesSize: 5,
        miniMapTop: 25,
        miniMapWidth: 250,
        namesColor: "#000000",
        namesFont: "ubuntu-bold",
        namesFontFamily: "Ubuntu",
        namesFontWeight: 700,
        namesScale: 0.9,
        namesStrokeColor: "#ffffff",
        safeAreaColor: "#ffffff",
        sectorsColor: "#ff2b77",
        sectorsFont: "ubuntu",
        sectorsFontFamily: "Ubuntu",
        sectorsFontSize: 940,
        sectorsFontWeight: 400,
        sectorsWidth: 6,
        sectorsX: 5,
        sectorsY: 5,
        skinsAlpha: 0.7,
        splitRangeColor: "#ffffff",
        statsHudColor: "#ffffff",
        strokeScale: 1,
        teammatesIndColor: "#ffffff",
        textAlpha: 1,
        timeHudColor: "#ff2b77",
        top5MassColor: "#ff2b77",
        virMassScale: 2,
        virusAlpha: 0.4,
        virusColor: "#3b3b3b",
        virusStrokeColor: "#ff2b77",
        virusStrokeSize: 10,
        customBackground: '',
        customCursor: ``
    },
    'sniikz-style': {
        name: `SniiKz's Style`,
        darkTheme: true,
        mainColor: `#01d9cc`,
        bgColor: `#000000`,
        bordersColor: '#ffffff',
        gridColor: `#00243e`,
        sectorsColor: '#00243e',
        namesColor: `#ffffff`,
        namesStrokeColor: '#000000',
        massColor: '#ffffff',
        massStrokeColor: `#000000`,
        virusColor: '#3b3b3b',
        virusStrokeColor: `#ffffff`,
        foodColor: `#5000ff`,
        teammatesIndColor: `#ffffff`,
        cursorTrackingColor: `#ffffff`,
        splitRangeColor: '#ffffff',
        safeAreaColor: `#ffffff`,
        dangerAreaColor: '#bf00aa',
        massScale: 4,
        foodSize: 1,
        bordersWidth: 40,
        sectorsWidth: 40,
        sectorsFontSize: 1200,
        cellsAlpha: 0.99,
        skinsAlpha: 0.7,
        virusAlpha: 0.4,
        virusStrokeSize: 10,
        menuPreset: `ogario-v3`,
        menuMainColor: `#fc0079`,
        menuBtnTextColor: `#ffffff`,
        menuPanelColor: '#050008',
        menuPanelColor2: `#1d0526`,
        menuTextColor: `#ffffff`,
        menuTextColor2: `#65458f`,
        btn1Color: '#4f0242',
        btn1Color2: `#3b0431`,
        btn2Color: `#6b0036`,
        btn2Color2: `#4d0227`,
        btn3Color: `#aa084e`,
        btn3Color2: `#80063b`,
        btn4Color: `#aa084e`,
        btn4Color2: '#8a063f',
        menuBg: `https://cdn.ogario.ovh/static/img/pattern.png`,
        menuOpacity: 1,
        hudMainColor: '#5974ff',
        hudColor: 'rgba(36,36,36,0.49)',
        hudTextColor: `#ffffff`,
        statsHudColor: `#ffffff`,
        timeHudColor: '#737373',
        top5MassColor: `#1fe000`,
        lbMeColor: '#bf00aa',
        lbTeammateColor: `#018cf6`,
        hudScale: 1.15,
        messageColor: 'rgba(0,0,0,0.4)',
        messageTextColor: `#e8e8e8`,
        messageTimeColor: '#545454',
        messageNickColor: '#05ff00',
        commandsColor: `rgba(36,36,36,0.9)`,
        commandsTextColor: `#ffffff`,
        commandsTimeColor: '#545454',
        commandsNickColor: `#ffffff`,
        chatBoxColor: `rgba(0,0,0,0.4)`,
        chatScale: 1,
        miniMapSectorsColor: '#ffffff',
        miniMapSectorColor: `#000000`,
        miniMapGuidesColor: `#ff00a8`,
        miniMapNickColor: `#ffffff`,
        miniMapNickStrokeColor: `#4d4d4d`,
        miniMapMyCellColor: '#f0ff3d',
        miniMapMyCellStrokeColor: `#acba07`,
        miniMapTeammatesColor: '#305eff',
        miniMapDeathLocationColor: '#2b2b2b',
        miniMapWidth: 250,
        miniMapSectorsOpacity: 0.1,
        miniMapNickSize: 9,
        miniMapNickStrokeSize: 0,
        miniMapMyCellSize: 5,
        miniMapMyCellStrokeSize: 0,
        miniMapTeammatesSize: 5,
        customBackground: '',
        customCursor: `https://cdn.ogario.ovh/static/img/cursors/cursor_01.cur`
    },
    'hkg-style': {
        name: `HKG Style`,
        darkTheme: true,
        mainColor: '#651fff',
        bgColor: `#000000`,
        bordersColor: `#ffffff`,
        gridColor: `#111111`,
        sectorsColor: `#111111`,
        namesColor: `#ffffff`,
        namesStrokeColor: `#000000`,
        massColor: `#ffffff`,
        massStrokeColor: `#000000`,
        virusColor: `#666666`,
        virusStrokeColor: `#666666`,
        foodColor: `#651fff`,
        hudMainColor: `#651fff`,
        statsHudColor: '#651fff',
        top5MassColor: '#651fff',
        timeHudColor: `#651fff`,
        messageNickColor: `#651fff`,
        commandsColor: `rgba(101,31,255,0.9)`,
        commandsTimeColor: `#651fff`,
        commandsTextColor: `#ffffff`,
        miniMapSectorsColor: '#ffffff',
        miniMapSectorColor: `#651fff`,
        miniMapGuidesColor: `#651fff`,
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: `#651fff`,
        miniMapTeammatesColor: '#651fff',
        miniMapDeathLocationColor: '#651fff',
        miniMapSectorsOpacity: 0.1
    },
    'agario-light': {
        name: `Agar.io Light`,
        darkTheme: false,
        mainColor: `#ffffff`,
        bgColor: `#f2fbff`,
        bordersColor: `#858a8c`,
        gridColor: `#ced6d9`,
        sectorsColor: '#ced6d9',
        namesColor: '#ffffff',
        namesStrokeColor: '#000000',
        massColor: `#ffffff`,
        massStrokeColor: '#000000',
        virusColor: `#33ff33`,
        virusStrokeColor: `#2de52d`,
        foodColor: '#2de52d',
        hudMainColor: `#ffffff`,
        statsHudColor: `#ffffff`,
        top5MassColor: `#ffffff`,
        timeHudColor: `#ffffff`,
        messageNickColor: '#ffffff',
        commandsColor: `rgba(255,255,255,0.9)`,
        commandsTimeColor: `#ffffff`,
        commandsTextColor: `#000000`,
        miniMapSectorsColor: `#ffffff`,
        miniMapSectorColor: '#ffffff',
        miniMapGuidesColor: '#ffffff',
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: '#ffffff',
        miniMapTeammatesColor: `#ffffff`,
        miniMapDeathLocationColor: `#ffffff`,
        miniMapSectorsOpacity: 0.25
    },
    'agario-dark': {
        name: `Agar.io Dark`,
        darkTheme: true,
        mainColor: `#ffffff`,
        bgColor: `#111111`,
        bordersColor: `#999999`,
        gridColor: `#333333`,
        sectorsColor: `#333333`,
        namesColor: `#ffffff`,
        namesStrokeColor: `#000000`,
        massColor: `#ffffff`,
        massStrokeColor: `#000000`,
        virusColor: `#33ff33`,
        virusStrokeColor: `#2de52d`,
        foodColor: `#2de52d`,
        hudMainColor: `#ffffff`,
        statsHudColor: '#ffffff',
        top5MassColor: `#ffffff`,
        timeHudColor: `#ffffff`,
        messageNickColor: `#ffffff`,
        commandsColor: `rgba(255,255,255,0.9)`,
        commandsTimeColor: `#ffffff`,
        commandsTextColor: '#ffffff',
        miniMapSectorsColor: `#ffffff`,
        miniMapSectorColor: `#ffffff`,
        miniMapGuidesColor: `#ffffff`,
        miniMapMyCellColor: `#ffffff`,
        miniMapMyCellStrokeColor: '#ffffff',
        miniMapTeammatesColor: `#ffffff`,
        miniMapDeathLocationColor: `#ffffff`,
        miniMapSectorsOpacity: 0.1
    }
};

var settings = {
    quickResp: true,
    autoResp: false,
    autoZoom: false,
    autoHideNames: true,
    autoHideMass: true,
    autoHideFood: false,
    autoHideFoodOnZoom: false,
    noNames: false,
    optimizedNames: true,
    hideMyName: true,
    hideTeammatesNames: false,
    showMass: true,
    optimizedMass: true,
    shortMass: true,
    virMassShots: true,
    hideMyMass: false,
    hideEnemiesMass: false,
    vanillaSkins: false,
    customSkins: true,
    myTransparentSkin: false,
    myCustomColor: false,
    transparentCells: false,
    transparentViruses: true,
    transparentSkins: false,
    showGrid: false,
    showBgSectors: false,
    showMapBorders: true,
    showGhostCells: true,
    showMiniMap: true,
    showMiniMapGrid: false,
    showMiniMapGuides: true,
    showMiniMapGhostCells: false,
    oneColoredTeammates: false,
    optimizedFood: false,
    rainbowFood: false,
    oppColors: false,
    oppRings: false,
    virColors: false,
    splitRange: false,
    virusesRange: false,
    textStroke: false,
    namesStroke: false,
    massStroke: false,
    cursorTracking: false,
    teammatesInd: false,
    mouseSplit: false,
    mouseFeed: false,
    mouseInvert: false,
    disableChat: false,
    hideChat: false,
    chatSounds: true,
    chatEmoticons: true,
    showChatBox: false,
    showChatImages: true,
    showChatVideos: true,
    showTop5: true,
    showTop5Sectors:false,
    showTargeting: false,
    showLbData: true,
    showTime: false,
    normalLb: false,
    centeredLb: false,
    fpsAtTop: true,
    showStats: true,
    showStatsMass: true,
    showStatsSTE: false,
    showStatsN16: false,
    showStatsFPS: true,
    showStatsPPS: true,
    blockPopups: false,
    streamMode: false,
    hideSkinUrl: false,
    showQuickMenu: true,
    showSkinsPanel: true,
    animation: 140,
    macroFeeding: 80,
    stickyCell:false,
    zoomSpeedValue: 0.9,
    messageSound: `https://cdn.ogario.ovh/static/sounds/notification_01.mp3`,
    commandSound: `https://cdn.ogario.ovh/static/sounds/notification_02.mp3`,
    virusSoundURL:'https://freesound.org/data/previews/163/163457_2263027-lq.mp3',
    virusSounds:false,
    leaderboardLength:10,
    renderQuality: 1,
    debug:false,
    mapLocalFix3:true,
    mapGlobalFix4:false,
    experimental1:false,
    cameraDelay:0,
    zoomSmoothness:10,
    showExtraMiniMapGuides:true,
};
var tempsett = {
    
}

let chatCommand = {
    comm1: textLanguage.comm1,
    comm2: textLanguage.comm2,
    comm3: textLanguage.comm3,
    comm4: textLanguage.comm4,
    comm5: textLanguage.comm5,
    comm6: textLanguage.comm6,
    comm7: textLanguage.comm7,
    comm8: textLanguage.comm8,
    comm9: textLanguage.comm9,
    comm0: textLanguage.comm0,
    comm10: textLanguage.comm10,
    comm11: textLanguage.comm11,
    comm12: textLanguage.comm12,
    comm13: textLanguage.comm13,
    comm14: textLanguage.comm14
};
const escapeChar = {
    '&': `&amp;`,
    '<': `&lt;`,
    '>': `&gt;`,
    '"': `&quot;`,
    '\'': '&#39;',
    '/': `&#x2F;`
};

const SkinExplain = [{
    name: `imgur.com`,
    url: `https://imgur.com/`,
    example: `https://i.imgur.com/xdmUp5N.png`,
    pattern: `https?:\/\/\w+\.imgur\.com\/\w{6,}\.(?:%file_ext%)\??\d*`
}, {
    name: `put.re`,
    url: 'https://put.re/',
    example: 'https://s.put.re/iYHAW65g.png',
    pattern: `https?:\/\/\w+\.put\.re\/\w{8,}\.(?:%file_ext%)`
}, {
    name: `postimages.org`,
    url: `https://postimages.org/`,
    example: 'https://i.postimg.cc/zzK0sRPg/xdmUp5N.png',
    pattern: 'https?:\/\/\w+\.postimg\.cc\/\w{8,}\/\w+\.(?:%file_ext%)'
}];

